feat(ci): Add workflow to run tests
famedly/traefik-certauthz pull request #4
Opened 2023-10-20 17:27 UTC by CherryKitten

2023-10-20 17:28 UTC, CherryKitten commented
@jcgruenhage needs actions enabled still

2024-02-29 10:47 UTC, jcgruenhage requested changes

2024-02-29 10:47 UTC, jcgruenhage commented on .github/workflows/go-test.yml
> +        uses: actions/checkout@v3
We should probably use `actions/checkout@v4` here due to the node16 deprecation

2024-03-11 10:12 UTC, jcgruenhage approved these changes

2024-03-11 11:43 UTC, merged